# Generated by Django 4.0.3 on 2022-04-06 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('pin_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserPinner',
            fields=[
                ('user_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_surname', models.CharField(max_length=100)),
                ('avatar', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('pin_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest.board')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pinterest.pin')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='user_pinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest.userpinner'),
        ),
    ]
