# Generated by Django 4.0.3 on 2022-04-12 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='board',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Pin',
        ),
        migrations.DeleteModel(
            name='UserPinner',
        ),
    ]
